<a href="https://colab.research.google.com/github/SHRUTHIHARIKRISH/python29/blob/main/numpy29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as pd

In [29]:
import numpy as np
a= np.array([1,2,3])
a.ndim        #gives the dimension of the array


1

In [30]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a.shape)   # (2,3)
print(a.ndim)    # 2
print(a.size)    # 6
print(a.dtype)   # int

(2, 3)
2
6
int64


In [31]:
import numpy as np
np.logspace(1, 3 ,3)  #start,stop, num of values needed

array([  10.,  100., 1000.])

In [32]:
import numpy as np
a=np.ones((2,3) ,dtype= int)
a
b=np.zeros((2,3))
b
c=np.full(3,29)   # ([29, 29, 29])
c




array([29, 29, 29])

In [33]:
import numpy as np

print(np.zeros((2, 3)))
print(np.ones((3, 2)))
print(np.arange(1, 10))
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [34]:
a = np.random.randint(1, 10, 5)
print(a)   #prints only random positive integers


[9 5 7 9 2]


In [35]:
arr = np.random.rand(10)
arr #-> random floats(0 to 1)

array([0.58604573, 0.01009286, 0.01903146, 0.67639977, 0.95466822,
       0.44767094, 0.33181009, 0.50948775, 0.56631456, 0.72802756])

In [36]:
arr = np.random.rand(2,3)
arr

array([[0.45352047, 0.29512425, 0.06276633],
       [0.04560413, 0.40364655, 0.36190836]])

In [37]:
arr = np.random.randn(2,3)  #can be any number which is 0,1-1,-5,2,4.. anything
arr #-> random floats from standard normal distribution

array([[-0.52714302,  0.07429559, -1.95177006],
       [-0.41197744,  0.28605324,  1.32428968]])

DATA TYPES

In [38]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.dtype

dtype('int64')

In [39]:
import numpy as np
arr=np.array([[1.2,2.2,3],[4,5,6]])
arr.dtype

dtype('float64')

TYPE CASTING


In [40]:
import numpy as np
list=[[1.2,2.2,3],[4,5,6]]
arr= np.array(list)
arr

array([[1.2, 2.2, 3. ],
       [4. , 5. , 6. ]])

astype() function

In [41]:
import numpy as np
arr=np.array([[1.2,2.2,3],[4,5,6]])
new_arr= arr.astype(int)#converts what ever in the arrat into mentioned type
#new_arr= arr.astype(float)  string cannot be converted
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
import numpy as np
arr = np.linspace(0,2,10) #start, stop, number of values
arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [43]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(matrix[1:  ,1: ])

[[5 6]
 [8 9]]


P1 Create a NumPy array with values: [5, 10, 15, 20]
👉 Print the data type

In [44]:
arr=np.array([[5,10,15,20]])
print(arr.dtype)

int64


In [45]:
arr=np.array([[[10, 20, 30]]])
a=np.astype(arr,float)
b=a.dtype
print(a)
print(b)

[[[10. 20. 30.]]]
float64


In [46]:
arr=np.array([[1.9, 2.1, 3.7]])
a=np.astype(arr,int)
b=a.dtype
print(a)
print(b)

[[1 2 3]]
int64


In [47]:
arr=np.array([[100,200,300]])
a=np.astype(arr,str)
b=a.dtype
print(a)
print(b)

[['100' '200' '300']]
<U21


In [48]:
a = np.array([1, 2, 3])
b = a.astype(float)
print(a.dtype)
print(b.dtype)

int64
float64


In [49]:
arr=np.array([[True, False, True]])
a=np.astype(arr,int)
b=a.dtype
print(a)
print(b)

[[1 0 1]]
int64


p2

In [50]:
arr=np.array([2, 4, 6, 8, 10])
print(arr)
print(arr.dtype)
print(arr.size)

[ 2  4  6  8 10]
int64
5


In [51]:
a=np.zeros((3,2))
b=np.ones((2,3))
print(a.shape)
print(b.shape)



(3, 2)
(2, 3)


In [52]:
a=np.arange(1, 11)
b=np.linspace(1, 10, 5,dtype=int)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7 10]


In [53]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[:4])

10
50
[10 20 30 40]


In [54]:
b = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(b[1,2])
print(b[0])
print(b[ :,1])


6
[1 2 3]
[2 5 8]


In [56]:
a = np.array([1,2,3,4])
print(a+5)
print(a*5)
print(np.sum(a))
print(np.mean(a))

[6 7 8 9]
[ 5 10 15 20]
10
2.5


In [64]:
a=np.random.randint(1,20,3)#from 1 to 20 , 3 random integers
a

array([ 8, 15,  9])

In [65]:
a = np.array([1,2,3,4,5,6])
b=np.reshape(a,(2,3))
c=np.reshape(a,(3,2))
print(c)
print(b)


[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [69]:
a = np.array([1,2,3])
b = a
c = a.astype(float)
print(a)
print(b)
print(c)
a[0]=100
a

[1 2 3]
[1 2 3]
[1. 2. 3.]


array([100,   2,   3])

Analyze marks of students using NumPy

In [77]:
marks=np.array([45, 67, 89, 34, 90, 76, 88])
avg=np.average(marks)
high=np.max(marks)
low=np.min(marks)
add=marks+5
greatest=marks[marks>75]
new_marks=np.astype(marks, float)


print(avg)
print(high)
print(low)
print(add)
print(greatest)
print(new_marks)

69.85714285714286
90
34
[50 72 94 39 95 81 93]
[89 90 76 88]
[45. 67. 89. 34. 90. 76. 88.]


In [94]:
arr=np.random.rand(10)
temp=arr*40
np.min(temp)
np.max(temp)
np.average(temp)
arrange=temp.reshape(5,2)
a=np.astype(arrange ,int)
a

array([[ 1, 20],
       [ 6, 19],
       [22, 28],
       [38,  8],
       [17, 22]])

In [97]:
a = np.array([10, np.nan, np.inf, 30])

# replace nan
a[np.isnan(a)] = 0
print(a)
# replace inf
a[np.isinf(a)] = 0
print(a)
#find finite values
a[np.isfinite(a)]
print(a)



[10.  0. inf 30.]
[10.  0.  0. 30.]
[10.  0.  0. 30.]
