<a href="https://colab.research.google.com/github/SHRUTHIHARIKRISH/python29/blob/main/numpy29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a= np.array([1,2,3])
a.ndim        #gives the dimension of the array


1

In [4]:
import numpy as np
a= np.array([[1,2,3],[4,5,6]])
print(a.shape)   # (2,3)
print(a.ndim)    # 2
print(a.size)    # 6
print(a.dtype)   # int

(2, 3)
2
6
int64


In [10]:
import numpy as np
np.logspace(1, 3 ,3)  #start,stop, num of values needed

array([  10.,  100., 1000.])

In [24]:
import numpy as np
a=np.ones((2,3) ,dtype= int)
a
b=np.zeros((2,3))
b
c=np.full(3,29)   # ([29, 29, 29])
c




array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
import numpy as np

print(np.zeros((2, 3)))
print(np.ones((3, 2)))
print(np.arange(1, 10))
print(np.linspace(0, 1, 5))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.  ]


In [2]:
a = np.random.randint(1, 10, 5)
print(a)   #prints only random positive integers


[1 6 5 2 2]


In [29]:
arr = np.random.rand(10)
arr #-> random floats(0 to 1)

array([0.39325769, 0.17378858, 0.14319823, 0.32152951, 0.75268324,
       0.24263908, 0.98505163, 0.08360146, 0.97667099, 0.90306575])

In [31]:
arr = np.random.rand(2,3)
arr

array([[0.89480077, 0.17415396, 0.91629419],
       [0.83425676, 0.51024907, 0.57007172]])

In [32]:
arr = np.random.randn(2,3)  #can be any number which is 0,1-1,-5,2,4.. anything
arr #-> random floats from standard normal distribution

array([[ 1.2198819 ,  1.47597034,  0.4160905 ],
       [-1.71590017, -0.55986746,  0.92421696]])

DATA TYPES

In [36]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
arr.dtype

dtype('int64')

In [38]:
import numpy as np
arr=np.array([[1.2,2.2,3],[4,5,6]])
arr.dtype

dtype('float64')

TYPE CASTING


In [40]:
import numpy as np
list=[[1.2,2.2,3],[4,5,6]]
arr= np.array(list)
arr

array([[1.2, 2.2, 3. ],
       [4. , 5. , 6. ]])

astype() function

In [41]:
import numpy as np
arr=np.array([[1.2,2.2,3],[4,5,6]])
new_arr= arr.astype(int)#converts what ever in the arrat into mentioned type
#new_arr= arr.astype(float)  string cannot be converted
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
import numpy as np
arr = np.linspace(0,2,10) #start, stop, number of values
arr

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [45]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

print(matrix[1:  ,1: ])

[[5 6]
 [8 9]]
